version: '3.3'
services:
  mysql_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'tm_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  neo4j:
    image: neo4j:5.21.0-community
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/secretgraph
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/import
      - neo4j_plugins:/plugins

  scrapy:
    build: .
    depends_on:
      - mysql_db
    volumes:
      - type: volume
        source: mydata
        target: /usr/src/app/tfmkt_scraper/tfmkt_scraper/data

volumes:
  my-db:
  mydata:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins: