version: '3.3'
services:
  mysql_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'tm_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci


  scrapy:
    build: .
    depends_on:
      - mysql_db
    volumes:
      - type: volume
        source: mydata
        target: /usr/src/app/tfmkt_scraper/tfmkt_scraper/data
volumes:
  my-db:
  mydata: